nome = input('Digite o seu nome completo: ')
print(f'Seu nome completo todo em maiúsculo é: {nome.upper()}')
print(f'Seu nome completo todo em minúsculo é: {nome.lower()}')
quantidade  = nome.split()
print(f'Seu nome completo tem {len(quantidade[0] + quantidade[1])}, letras!')
print(f'Seu primeiro nome é: {quantidade[0]} e ele tem {len(quantidade[0])}')
