times_brasileirao = ('Palmeiras', 'Flamengo', 'Atlético Mineiro', 'Fortaleza', 'Bragantino', 'Athletico Paranaense', 'Ceará', 'Corinthians', 'Internacional', 'Santos', 'Chapecoense')


print("=||="*12)
print('')
print("Os primeiros cinco colocados são: ")
print(times_brasileirao[0:5])
print("=||="*12) 
print('')
print("=||="*12)
print("Os últimos quatro colocados são: ")
print(times_brasileirao[-4:])
print("=||="*12) 
print('')
print("=||="*12) 
indice_chapecoence= times_brasileirao.index('Chapecoense')
print('O Chapecoense está na colocação: ')
print(indice_chapecoence, '° colocação')
print("=||="*12) 
print('')
print("=||="*12) 
print('Os times ordenados são: ')
print(sorted(times_brasileirao))
print("=||="*12) 
print('')