print("=//==//===//==//===//==//==")
print('')
print("        ESCOLHA")
print('''   [1] Cara [2] Coroa''')
print('')
print("=//==//===//==//===//==//==")
print('')
num = int(input("Digite a sua escolha: "))